### ISSUE TITLE
ARM ADS 1.2

### ISSUE THREAD

**Issue by DavidTheTech** [cotodevel/NesDS#1]
Where do I find the "ARM ADS 1.2" as said in the readme file

**Comment by cotodevel** [comment]
What is "ARM ADS 1.2" again? I have never seen that. What is exactly your issue? (does it even exists?)

**Comment by DavidTheTech** [comment]
In the readme file it says "nesDS was compiled with ARM ADS 1.2.
To build it, open the project file (nesDS.mcp) and click Project -> Make."

**Comment by cotodevel** [comment]
Try to follow the instructions at the updated readme (the one that loads once you reach NesDS github page).
