### ISSUE TITLE
Update NesDS for devkitarm r46 and libnds 1.6.2

### ISSUE THREAD

**Issue by ApacheThunder** [cotodevel/NesDS#2]
I'm sure if WinterMute found this, he will be suggesting the same thing. Please update this project to compile on devkitarm r46 and libnds 1.6.2.

Review this fork I made to point out the actual parts that currently cause issues for r46:

https://github.com/ApacheThunder/NesDS

Note my commits are just hack job workarounds. I would like to see NesDS properly fixed. I also had to strip the disk folder out (I think it's a custom replacement to devkitarm's fat library?...why exactly did you do that?) because it breaks SD access on DSi/3DS in TWL mode. Either implement the missing emmc support or revert back to the standard fat libraries provided by devkitarm. :D

Refer to memory.s in arm9 source. It's the source of the memory related error you will be getting when you attempt to compile it for r46 (there's also a missing function no longer in libnds 1.6.2 that I manually defined. You could do what I did or rework it to use what libnds 1.6.2 might have intended in it's place)

 I don't know how to fix this properly myself. Hence I am mentioning it here in hopes you can fix the problem now that I've narrowed down where in the source code this problem crops up. While Wifi stuff will most likely not work in TWL mode, it would be nice for folks to have a proper mostly functional solution for running NES stuff from DSi/3DS SD card. Not everyone has or wants to use a flashcart for this. :P

**Comment by cotodevel** [comment]
I am not supporting devkitpro anymore. I will support my own toolchains from now on, so if the developer wants that is something up to him/her to do. :0

**Comment by cotodevel** [comment]
Oh, also check the other answers, compile a standalone dldi driver with dsi sd drivers (re´d by nocash??) and use the other emu SD drivers. It should work (:

**Comment by ApacheThunder** [comment]
Hmm DLDI driver for DSi SD never worked on hardware last I checked. Arm7 has exclusive access to SD. Arm9 DLDI alone would not be enough to get around that. That's why Ahezard made a complicated patcher thing that setups up code in unused ram to handle the arm7/arm9 communication needed for SD access on older homebrew. (though his newer versions of nds-bootstrap that implemented retail rom support broke this for homebrew. His 0.2 version was the last version this still worked in I believe)

So DLDI for DSi SD I don't think is as simple as it was originally going to be. :(

**Comment by cotodevel** [comment]
Indeed. But if you add that arm7/arm9 handler (in the form of a dldi 7 + arm9 handler) like it appears to be done now, then it shoudl work. (I am doing NDS stuff) so .. yeah that. :0

**Comment by ApacheThunder** [comment]
I see. My TWL exclusive build of NesDS should be fine for now I guess. I tested it and it booted the 700KB+ size Samari bootleg rom just fine. So for TWL mode, everything looks to run fine with the dsi spec file. :P
